### ISSUE TITLE
Identifier rejected error when connecting to broker

### ISSUE THREAD

**Issue by kulkarniatharv** [krylovsk/mqtt-benchmark#20]
When I try to connect to the broker, the error `error connecting to the broker: Identifier rejected` is thrown

![image](https://user-images.githubusercontent.com/15829308/123476706-b2ab5a00-d61a-11eb-88b4-2c2973964e1f.png)

I'm using Windows 10 and PowerShell

**Comment by kulkarniatharv** [comment]
Also when I type in `.\mqtt-benchmark.exe -h` this is what comes up. There is no `-client-prefix`, `-client-key`, `-client-cert`. 
Why is this so?
![image](https://user-images.githubusercontent.com/15829308/123483681-bfcd4680-d624-11eb-9151-fabd3fc8dcff.png)

**Comment by krylovsk** [comment]
Hey @kulkarniatharv, the first error suggests that broker refuses the connection and that usually happens when ClientID is empty and clean session flag is false. Neither of that should be the case here as ClientID is generated and clean session is always set to true.

Which broker are you using? Are you sure the broker is running and operational?

The second error is because with go modules by default `go get` and `go install` fetch the latest release (here [v0.1.1](https://github.com/krylovsk/mqtt-benchmark/releases/tag/v0.1.1)) and I haven't gotten to finalize v0.2 to release it. 
Please install the tool via `go install github.com/krylovsk/mqtt-benchmark@master` for now.

**Comment by kulkarniatharv** [comment]
The broker that I'm using is HiveMQ CE. Yes, the broker is operational.

The new tool that you mentioned `go install github.com/krylovsk/mqtt-benchmark@main` seems to resolve all the errors mentioned above. 

Thanks!
